### ISSUE TITLE
Service restart failure 

### ISSUE THREAD

**Issue by akshatgit** [paypal/NNAnalytics#132]
Restarted NNA-service after changing the memory constriants of jvm. Resulted in the following error in fetching edits and thereby failed to load namesystem
```
java.io.IOException: There appears to be a gap in the edit log.  We expected txid 4977001276, but got txid 4988194353.
	at org.apache.hadoop.hdfs.server.namenode.MetaRecoveryContext.editLogLoaderPrompt(MetaRecoveryContext.java:94)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLogLoader.loadEditRecords(FSEditLogLoader.java:215)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLogLoader.loadFSEdits(FSEditLogLoader.java:143)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.loadEdits(FSImage.java:832)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.loadFSImage(FSImage.java:687)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:294)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:976)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:681)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeLoader.load(NameNodeLoader.java:381)
	at com.paypal.namenode.WebServerMain.lambda$init$45(WebServerMain.java:1728)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zero45** [comment]
Hey @akshatgit -- I think what happened here is that you restarted your NNA instance without going to "Admin -> Namespace -> Save Namespace"; since you didn't save your namespace before shutting down NNA fell behind the JournalNodes and was unable to catch back up.

The workaround to restore service right now is to do "Admin -> Namespace -> Fetch Namespace" and then restart again once that completes. In the future, before shutting down, be sure to run a `/saveNamespace`, either by hitting the endpoint directly or by the UI.

**Comment by zero45** [comment]
As some additional context -- NNA does not persist the edit log as it receives it. If you check the NNA namespace directory you'll see it only contains the FsImage. This is intentional in order to keep NNA as light as possible.

**Comment by akshatgit** [comment]
Thank you for the much needed explanation. I restarted the namespace without saving it, the workaround was helpful in restoring it.

**Comment by zero45** [comment]
Thanks @akshatgit! Let me know if I can close this.

Also, documentation regarding this is located here: https://nnanalytics.readthedocs.io/en/latest/Getting_Started/How_To_Run/.

**Comment by akshatgit** [comment]
Thanks for the reference, let's close this issue.
