### ISSUE TITLE
the UI page return no data 

### ISSUE THREAD

**Issue by silvermissile** [paypal/NNAnalytics#293]
Env:
cdh5.14.2 (Hadoop 2.6.0-cdh5.14.0)
Nna-analysis (buid with hadoop2.7)

With my test Hadoop 2.6.0-cdh5.14.0 env , everything is OK 
![image](https://user-images.githubusercontent.com/5319647/73467045-b2734480-43bd-11ea-8798-bf22bb7a34af.png)

**BUT 
When I  deploy NNAnalysis on my pro Hadoop 2.6.0-cdh5.14.0  cluster : every page show no data about my hdfs cluster**

![image](https://user-images.githubusercontent.com/5319647/73467222-fcf4c100-43bd-11ea-9df1-e3ddd4c1de04.png)

After a few  minutes  , the UI  can hardly load  
And  it  take dozen seconds for curl cmd to respose:
curl http://id-cdh-master-190:4568/info

Current active connections: 1
Current running queries:
/info:default_unsecured_user

Current system time (ms): 1580399570474
Ready to service queries: false
Guarding against queries: false
Ready to service history: true
Ready to service suggestions: false

Current suggestion analysis state: sleep
Current suggestion analysis percentage: 0.0%

Cached directories for analysis::
Cached directories size: 0

Cached queries for analysis::
Cached queries size: 0

And I think jvm opts enough  member : 
```
Jps -lmv 
7006 org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain -XX:ParallelGCThreads=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:NewSize=8960m -XX:MaxNewSize=8960m -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:CMSInitiatingOccupancyFraction=70 -XX:+UseCMSInitiatingOccupancyOnly -Xms78566m -Xmx78566m -XX:+PrintFlagsFinal -XX:+PrintReferenceGC -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:/var/log/nn-analytics/gc.log-202001301536 -Dhadoop.log.dir=/var/log/nn-analytics -Dhadoop.log.file=nn-analytics.log -Dhadoop.root.logger=INFO,DRFA -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8004 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dnamenode.metrics.logger=INFO,NNMETRICSRFA -Dorg.mortbay.jetty.Request.maxFormContentSize=-1 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

```

the nn-analytics.out
```
intx hashCode                                  = 5                                   {product}
Listening for transport dt_socket at address: 5005
[main] WARN org.apache.hadoop.hdfs.server.namenode.analytics.ApplicationConfiguration - Failed to load old properties file: security.
properties, due to: java.lang.NullPointerException. Ignore if you are using application.properties.
[main] INFO org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain - Running web server in HTTP mode.
[main] INFO org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain - Disabling web authentication.
[main] INFO org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain - Disabling web authorization.
[main] INFO spark.staticfiles.StaticFilesConfiguration - External StaticResourceHandler configured with folder = /usr/local/nn-analyt
ics/webapps/nna
[Thread-1] INFO org.eclipse.jetty.util.log - Logging initialized @548ms
[Thread-1] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-1] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4568
[Thread-1] INFO org.eclipse.jetty.server.Server - jetty-9.3.6.v20151106
[Thread-1] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@4dd8c88e{HTTP/1.1,[http/1.1]}{0.0.0.0:4568}
[Thread-1] INFO org.eclipse.jetty.server.Server - Started @621ms
log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB6FA27B7DB7.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Starting with QueryEngine implementation: org.apache.hadoop.hdfs.
server.namenode.JavaStreamQueryEngine
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Setting: dfs.block.access.token.enable to: false
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Setting: dfs.ha.log-roll.period to: -1
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Setting: dfs.ha.standby.checkpoints to: false
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Setting: dfs.content-summary.limit to: 0
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Setting: dfs.namenode.name.dir to: /usr/local/nn-analytics/dfs/na
me
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Unsetting: dfs.namenode.inode.attributes.provider.class
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - FSImage auto-fetched in: 27470 ms.
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Loading with configuration: Configuration: core-default.xml, core
-site.xml, hdfs-default.xml, hdfs-site.xml, hdfs-default.xml, hdfs-site.xml
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - FileSystem seen as: hdfs://nameservice1
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Loading image from: /usr/local/nn-analytics/dfs/name
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - dfs.namenode.startup.delay.block.deletion.sec is set to 000:
00:00:00.000
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - The block deletion will start around 2020 Jan 30 15:37:01
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - dfs.block.access.token.enable=false
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - defaultReplication         = 3
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - maxReplication             = 512
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - minReplication             = 1
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - maxReplicationStreams      = 2
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - shouldCheckForEnoughRacks  = false
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - replicationRecheckInterval = 3000
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - encryptDataTransfer        = false
[main] INFO org.apache.hadoop.hdfs.server.blockmanagement.BlockManager - maxNumBlocksToLog          = 1000
[main] INFO org.apache.hadoop.hdfs.server.namenode.FSDirectory - ACLs enabled? false
[main] INFO org.apache.hadoop.hdfs.server.namenode.FSDirectory - XAttrs enabled? true
[main] INFO org.apache.hadoop.hdfs.server.namenode.FSDirectory - Maximum size of an xattr: 16384
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNode - Caching file names occuring more than 10 times
[main] INFO org.apache.hadoop.hdfs.server.namenode.top.metrics.TopMetrics - NNTop conf: dfs.namenode.top.window.num.buckets = 10
[main] INFO org.apache.hadoop.hdfs.server.namenode.top.metrics.TopMetrics - NNTop conf: dfs.namenode.top.num.users = 10
[main] INFO org.apache.hadoop.hdfs.server.namenode.top.metrics.TopMetrics - NNTop conf: dfs.namenode.top.windows.minutes = 1,5,25
[main] INFO org.apache.hadoop.hdfs.StateChange - STATE* Safe mode is ON.
It was turned on manually. Use "hdfs dfsadmin -safemode leave" to turn safe mode off.
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - FSImage loaded in: 133267 ms.
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Loaded in 23972380 Inodes
[main] INFO org.apache.hadoop.hdfs.server.namenode.QueryEngine - Filtering inodes with implementation: org.apache.hadoop.hdfs.server.
namenode.ConcurrentHashMapINodeCollection
```

**questions :**
Why  no data   return ?
how  can I  debug  this  problem？

**Comment by silvermissile** [comment]
![image](https://user-images.githubusercontent.com/5319647/73543332-aea0fa00-4471-11ea-9233-110f7c3cc038.png)

sucks happen at the line above  showed by  log file above.
eventually   OOM happen 
``` 
	at org.apache.hadoop.hdfs.server.namenode.ConcurrentHashMapINodeCollection.filterINodes(ConcurrentHashMapINodeCollection.java:36)
	at org.apache.hadoop.hdfs.server.namenode.AbstractQueryEngine.filterINodes(AbstractQueryEngine.java:113)
	at org.apache.hadoop.hdfs.server.namenode.AbstractQueryEngine.handleGSet(AbstractQueryEngine.java:95)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeLoader.load(NameNodeLoader.java:377)
	at org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain.init(WebServerMain.java:2035)
	at org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain.init(WebServerMain.java:191)
	at org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain.init(WebServerMain.java:184)
	at org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain.main(WebServerMain.java:170)
Caused by: java.lang.OutOfMemoryError: Java heap space
[qtp2137527048-33] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@3440b622 in qtp2137527048{STARTED,8<=8<=200,i=2,q=0}
```

**Comment by pjeli** [comment]
Ah very likely it is failing to load the FsImage. Rule of thumb is to give it as much heap in the `nna_env` file as you do on your real NameNode. Please raise your heap size.

**Comment by pjeli** [comment]
Oh interesting - are you running the lastest master code and not the releases? I see `ConcurrentHashMapINodeCollection` in your stacktrace.

**Comment by pjeli** [comment]
You will not see any data if the FsImage does not load. Likely the slowness you are running into is due to the GC that NNA is going into. However I see you are only loading in 24M INodes; 70+ GB should be enough. For starters, please raise the heap size for now; try maybe 100G if you can.

**Comment by pjeli** [comment]
Since you are using the latest version please try one of the other INodeCollectionFilters as explained at the bottom of the documentation, here: [https://github.com/paypal/NNAnalytics/blob/master/docs/Getting_Started/How_To_Configure.md](https://github.com/paypal/NNAnalytics/blob/master/docs/Getting_Started/How_To_Configure.md).

By default it is set to use the ConcurrentHashMap which might be too heavy for a small number of INodes; try either the regular HashSet, Trove, or the Eclipse set.

**Comment by pjeli** [comment]
As a last resort, if you are still facing issues - please use one of the releases instead. It could be that there is an issue with using the latest code. The releases are deployed on large clusters and are already battle tested.

**Comment by silvermissile** [comment]
First of ALL ,thank you for your guide patiently . I finally  got  it  working  by using  release verson 1.6.6.



Yes  , I used  the newest  master branch verison ,and build myself.

When I add config :
`nna.inode.collection.impl=org.apache.hadoop.hdfs.server.namenode.HashMapINodeCollection`

Still meet this :
``` 
[main] INFO org.apache.hadoop.hdfs.StateChange - STATE* Safe mode is ON.
It was turned on manually. Use "hdfs dfsadmin -safemode leave" to turn safe mode off.
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - FSImage loaded in: 193365 ms.
[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Loaded in 25459445 Inodes
[main] INFO org.apache.hadoop.hdfs.server.namenode.QueryEngine - Filtering inodes with implementation: org.apache.hadoop.hdfs.server.namenode.HashMapINodeCollection


[main] ERROR org.apache.hadoop.hdfs.server.namenode.analytics.WebServerMain - FATAL
java.lang.OutOfMemoryError
```
As limit of node memery , I did not  set heap size  bigger.

**Comment by pjeli** [comment]
Interesting - well thank you for you the information. There must be some sort of memory bug with the INodeCollectionFilter patch. I will take a look at it. Glad you got it working!

**Comment by pjeli** [comment]
I am re-purposing this issue to reflect the `Out of memory` issues you were seeing from using the `master` branch.

**Comment by pjeli** [comment]
I have uncovered the issue and will be issuing a PR shortly. The bug was due to dangling references that were not being GC'd properly. What is odd is that the memory cost seemed to be exponential when it should have been double. Regardless though I was able to solve everything by limiting the INodeFilter implementations to being just pure logic with no kept state.

**Comment by vinaygulani1** [comment]
@silvermissile - I am getting fsimage version issue while starting NNA with  Hadoop 2.6.0-CDH-5.16. namenode layout version is -60 (with CDH-5.16) and its expecting -63 when I build NNA with Hadoop-2.7.0. Have you also faced the similar issue? 
I know its not relevant to this issue, just posting it here as I noticed you are also using CDH.

Here are the logs for error:
`[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Failed to load namesystem: {}
org.apache.hadoop.hdfs.server.common.IncorrectVersionException: Unexpected version of storage directory /hadoop/nn-analytics/dfs/name. Reported: -60. Expecting = -63.`

**Comment by silvermissile** [comment]
> @silvermissile - I am getting fsimage version issue while starting NNA with Hadoop 2.6.0-CDH-5.16. namenode layout version is -60 (with CDH-5.16) and its expecting -63 when I build NNA with Hadoop-2.7.0. Have you also faced the similar issue?
> I know its not relevant to this issue, just posting it here as I noticed you are also using CDH.
> 
> Here are the logs for error:
> `[main] INFO org.apache.hadoop.hdfs.server.namenode.NameNodeLoader - Failed to load namesystem: {} org.apache.hadoop.hdfs.server.common.IncorrectVersionException: Unexpected version of storage directory /hadoop/nn-analytics/dfs/name. Reported: -60. Expecting = -63.`

This seems to be imcomplitable problem  . 
I  use did not meet  this name layout issus   with both release  and self -build version
