### ISSUE TITLE
Suggestion reload can fail

### ISSUE THREAD

**Issue by zero45** [paypal/NNAnalytics#88]
On large instances of NNA, the suggestion report can fail with the following stacktrace:
```
[pool-2-thread-1] INFO org.apache.hadoop.hdfs.server.namenode.NNLoader - Suggestion reload failed: {}
java.lang.NullPointerException
        at sun.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.Nodes.collectLong(Nodes.java:404)
        at java.util.stream.LongPipeline.evaluateToNode(LongPipeline.java:140)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:540)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.LongPipeline.toArray(LongPipeline.java:484)
        at org.apache.hadoop.hdfs.server.namenode.NNLoader.fetchDataViaCpu(NNLoader.java:857)
        at org.apache.hadoop.hdfs.server.namenode.NNLoader.binMappingHistogram(NNLoader.java:989)
        at org.apache.hadoop.hdfs.server.namenode.NNLoader.parentDirHistogramCpu(NNLoader.java:1639)
        at org.apache.hadoop.hdfs.server.namenode.cache.SuggestionsEngine.reloadSuggestions(SuggestionsEngine.java:267)
        at org.apache.hadoop.hdfs.server.namenode.NNLoader.lambda$initReloadThreads$110(NNLoader.java:2143)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```
Luckily such a failure is harmless as the report will just re-run and hopefully be successful the next time around. However we should really handle this within NNA as the re-run cost is time delay in reporting.

**Comment by zero45** [comment]
I've pretty much nailed down the problem to being related to concurrently reading the INode set while it is being modified underneath. More analysis to come.
